version: "3.9"
services:
  web:
    build: .
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app.db
      - SECRET_KEY=${SECRET_KEY:-change-me}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-change-me-too}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
