name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set environment variables for testing
      - name: Set environment variables
        run: |
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///:memory:" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=test-jwt-secret" >> $GITHUB_ENV

      # Run tests
      - name: Run tests
        run: |
          pytest -q --disable-warnings --maxfail=1

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
