# .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///:memory:" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=test-jwt-secret" >> $GITHUB_ENV

      - name: Run tests
        run: pytest -q --disable-warnings
